apiVersion: v1
kind: Service
metadata:
  labels:
    component: cache
    name: redis
  name: redis
  namespace: kbench-pod-namespace
spec:
  ports:
  - nodePort: 31115
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
  type: LoadBalancer
